'use client';

/* eslint-disable @typescript-eslint/no-non-null-assertion -- legacy non-null assertions in command builders */

import {
  Activity,
  AlertTriangle,
  ArrowRightLeft,
  ClipboardCheck,
  Code2,
  Files,
  FileSearch,
  GitBranch,
  GitPullRequest,
  ListTodo,
  MessagesSquare,
  MessageSquare,
  Pencil,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  StopCircle,
  Terminal,
  Trash2,
} from 'lucide-react';
import { useMemo } from 'react';
import { SiGithub } from 'react-icons/si';
import { toast } from 'sonner';

import type { CommandItem, SettingsTab } from './types';
import { toTitleCase } from '../AgentPanel/PromptViewerModal';
import { useCommandFavorites } from '../../features/run-command/hooks/useCommandFavorites';
import { useCommandUsage } from '../../features/run-command/hooks/useCommandUsage';
import type { SavedCommand, SavedCommandScope } from '../../types/savedCommand';
import {
  formatSavedCommandPaletteLabel,
  savedCommandScopeKeywords,
} from '../../types/savedCommand';

export type { SettingsTab };

export type { SavedCommand };

interface UseCommandPaletteCommandsProps {
  onOpenSettings: (tab: SettingsTab) => void;
  onOpenEventStream: () => void;
  /** @deprecated Use onSwitchToSourceControl instead. */
  onOpenGitPanel?: (() => void) | null;
  onOpenBacklog: () => void;
  onOpenPendingReview: () => void;
  /** Opens the create-backlog-item modal (BacklogCreateModal) */
  onCreateBacklogItem?: (() => void) | null;
  /** Navigation callbacks */
  onOpenChatroomSwitcher: () => void;
  onCreateNewChatroom?: (() => void) | null;
  onOpenFileSelector: () => void;
  /** Workspace action callbacks — conditionally available (legacy single-workspace) */
  onOpenInVSCode?: (() => void) | null;
  onOpenInGitHubDesktop?: (() => void) | null;
  onOpenPROnGitHub?: (() => void) | null;
  /** @deprecated Use onSwitchToPullRequests instead. */
  onOpenPRReview?: (() => void) | null;
  onViewGitHubPullRequests?: (() => void) | null;
  onViewGitHubRepository?: (() => void) | null;
  /** @deprecated Use onSwitchToSourceControl instead. */
  onOpenWorkspaceDetails?: (() => void) | null;
  /** Switch to the Source Control activity view */
  onSwitchToSourceControl?: (() => void) | null;
  /** Switch to the Pull Requests activity view */
  onSwitchToPullRequests?: (() => void) | null;
  /** Runnable commands for matching favorites to scripts */
  runnableCommands?: { name: string; script: string; source: string }[];
  /** Callback to open the Processes panel with a specific command selected */
  onOpenProcessesPanelWithCommand?: (commandName: string) => void;
  /** Callback to directly execute a command (run + open terminal) */
  onRunCommand?: (commandName: string, script: string) => void;
  /** Callback to open the Processes panel */
  onOpenProcessesPanel?: () => void;
  /** Callback to switch to Explorer view */
  onShowExplorer?: (() => void) | null;
  /** Callback to open agentic search */
  onOpenAgenticSearch?: (() => void) | null;
  /** Callback to switch to Messages view */
  onShowMessages?: () => void;
  /** Callback to toggle chat in split panel (explorer view only) */
  onToggleChatSplitPanel?: (() => void) | null;
  /** Callback to start all remote agents with their last config */
  onStartAllRemoteAgents?: (() => void) | null;
  /** Callback to stop all remote agents */
  onStopAllRemoteAgents?: (() => void) | null;
  /** Callback to restart all remote agents (starts if stopped, restarts if running) */
  onRestartAllRemoteAgents?: (() => void) | null;
  /** Team roles eligible for per-role restart commands (caller excludes user/enhancer) */
  restartableAgentRoles?: string[];
  /** Restart a single remote agent by role */
  onRestartRemoteAgent?: ((role: string) => void) | null;
  /**
   * Per-workspace command items generated by WorkspaceCommandsAggregator.
   * When provided, these replace the legacy single-workspace action commands
   * (onOpenInVSCode, onOpenInGitHubDesktop, etc.).
   */
  workspaceCommands?: CommandItem[];
  /** Callback to open the Create Command modal (optional default scope) */
  onCreateCommand?: ((defaultScope?: SavedCommandScope) => void) | null;
  /** Saved commands to show in the command palette */
  savedCommands?: SavedCommand[];
  /** Callback to execute a saved command (send its prompt as a message) */
  onExecuteSavedCommand?: ((cmd: SavedCommand) => void) | null;
  /** Callback to edit a saved command */
  onEditSavedCommand?: ((cmd: SavedCommand) => void) | null;
  /** Callback to delete a saved command */
  onDeleteSavedCommand?: ((commandId: string, name: string) => void) | null;
  /** The commandId currently awaiting delete confirmation (if any) */
  confirmingDeleteCommandId?: string | null;
  /** Force the daemon to immediately re-push observed workspace state (git status, recent commits, PRs). */
  onRefreshWorkspaceState?: (() => void) | null;
}

/**
 * Hook that builds the list of commands for the command palette.
 *
 * Provides panel navigation commands and workspace action commands.
 * Action commands are conditionally included based on workspace availability.
 */
export function useCommandPaletteCommands({
  onOpenSettings,
  onOpenEventStream,
  onOpenGitPanel,
  onOpenBacklog,
  onOpenPendingReview,
  onCreateBacklogItem,
  onOpenChatroomSwitcher,
  onCreateNewChatroom,
  onOpenFileSelector,
  onOpenInVSCode,
  onOpenInGitHubDesktop,
  onOpenPROnGitHub,
  onOpenPRReview,
  onViewGitHubPullRequests,
  onViewGitHubRepository,
  onOpenWorkspaceDetails,
  runnableCommands,
  onOpenProcessesPanelWithCommand,
  onRunCommand,
  onOpenProcessesPanel,
  onShowExplorer,
  onShowMessages,
  onToggleChatSplitPanel,
  workspaceCommands,
  onStartAllRemoteAgents,
  onStopAllRemoteAgents,
  onRestartAllRemoteAgents,
  restartableAgentRoles,
  onRestartRemoteAgent,
  onCreateCommand,
  savedCommands,
  onExecuteSavedCommand,
  onEditSavedCommand,
  onDeleteSavedCommand,
  confirmingDeleteCommandId,
  onRefreshWorkspaceState,
  onSwitchToSourceControl,
  onSwitchToPullRequests,
  onOpenAgenticSearch,
}: UseCommandPaletteCommandsProps): CommandItem[] {
  const { favorites } = useCommandFavorites();
  const { clearUsage } = useCommandUsage();

  return useMemo<CommandItem[]>(() => {
    const commands: CommandItem[] = [];

    // ─── Saved Commands (custom user prompts) ──────────────────────
    if (savedCommands && savedCommands.length > 0 && onExecuteSavedCommand) {
      for (const cmd of savedCommands) {
        commands.push({
          id: `saved-cmd-${cmd._id}`,
          blacklistKey: `saved-cmd:${cmd.name}`,
          label: formatSavedCommandPaletteLabel(cmd.name, cmd.scope),
          icon: <MessageSquare size={14} />,
          category: 'Commands',
          keywords: [cmd.name, ...savedCommandScopeKeywords(cmd.scope)],
          action: () => onExecuteSavedCommand(cmd),
          secondaryActions: [
            ...(onEditSavedCommand
              ? [
                  {
                    id: `saved-cmd-edit-${cmd._id}`,
                    label: 'Edit',
                    icon: <Pencil size={12} />,
                    action: () => onEditSavedCommand(cmd),
                  },
                ]
              : []),
            ...(onDeleteSavedCommand
              ? [
                  {
                    id: `saved-cmd-delete-${cmd._id}`,
                    label: confirmingDeleteCommandId === cmd._id ? 'Confirm?' : 'Delete',
                    icon:
                      confirmingDeleteCommandId === cmd._id ? (
                        <AlertTriangle size={12} />
                      ) : (
                        <Trash2 size={12} />
                      ),
                    action: () => onDeleteSavedCommand(cmd._id, cmd.name),
                  },
                ]
              : []),
          ],
        });
      }
    }

    // ─── Favorites (favourited commands from process manager) ────────
    if (runnableCommands) {
      for (const cmd of runnableCommands) {
        if (favorites.has(cmd.name)) {
          commands.push({
            id: `fav-${cmd.name}`,
            label: cmd.name,
            icon: <Terminal size={14} />,
            category: 'Commands',
            // showOutputInline: true causes CommandPalette to call inlineCommand.run()
            showOutputInline: true,
            script: cmd.script,
            // action is a fallback for non-inline environments
            action: () => {
              if (onRunCommand) {
                onRunCommand(cmd.name, cmd.script);
              } else if (onOpenProcessesPanelWithCommand) {
                onOpenProcessesPanelWithCommand(cmd.name);
              }
            },
          });
        }
      }
    }

    // ─── Navigate (shown first) ──────────────────────────
    commands.push({
      id: 'nav-switch-chatroom',
      label: 'Chatroom: Switch',
      icon: <ArrowRightLeft size={14} />,
      category: 'Navigate',
      shortcut: '⌘K',
      action: onOpenChatroomSwitcher,
    });

    if (onCreateNewChatroom) {
      commands.push({
        id: 'nav-new-chatroom',
        label: 'New Chatroom',
        icon: <Plus size={14} />,
        category: 'Navigate',
        keywords: ['new', 'create', 'chatroom', 'new chatroom'],
        action: onCreateNewChatroom,
      });
    }

    // ─── Create Command actions ───────────────────────────────────
    if (onCreateCommand) {
      commands.push({
        id: 'action-create-chatroom-command',
        label: 'Chatroom: Create Command',
        icon: <Plus size={14} />,
        category: 'Actions',
        keywords: ['new', 'create', 'command', 'prompt', 'saved', 'chatroom', 'local'],
        action: () => onCreateCommand('chatroom'),
      });
      commands.push({
        id: 'action-create-user-command',
        label: 'User: Create Command',
        icon: <Plus size={14} />,
        category: 'Actions',
        keywords: ['new', 'create', 'command', 'prompt', 'saved', 'user', 'global', 'personal'],
        action: () => onCreateCommand('user'),
      });
    }

    commands.push({
      id: 'nav-go-to-file',
      label: 'Chatroom: Go to File',
      icon: <FileSearch size={14} />,
      category: 'Navigate',
      shortcut: '⌘P',
      action: onOpenFileSelector,
    });

    if (onOpenAgenticSearch) {
      commands.push({
        id: 'nav-agentic-search',
        label: 'Agentic Search',
        icon: <Search size={14} />,
        category: 'Navigate',
        shortcut: '⌘⇧F',
        keywords: ['search', 'ask', 'find', 'agentic', 'codebase', 'question'],
        action: onOpenAgenticSearch,
      });
    }

    // ─── Workspace Actions ────────────────────────────────
    // When workspaceCommands is provided (multi-workspace mode), use those.
    // Otherwise fall back to legacy single-workspace callbacks.
    if (workspaceCommands && workspaceCommands.length > 0) {
      commands.push(...workspaceCommands);
    } else {
      // Legacy single-workspace commands (backward compatible)
      if (onOpenInVSCode) {
        commands.push({
          id: 'action-open-vscode',
          label: 'Machine: Open in VS Code',
          icon: <Code2 size={14} />,
          category: 'Actions',
          action: onOpenInVSCode,
        });
      }

      if (onOpenInGitHubDesktop) {
        commands.push({
          id: 'action-open-github-desktop',
          label: 'Machine: Open in GitHub Desktop',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          action: onOpenInGitHubDesktop,
        });
      }

      if (onViewGitHubPullRequests) {
        commands.push({
          id: 'action-view-github-prs',
          label: 'Github: View My Pull Requests',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          keywords: ['PR', 'PRs'],
          action: onViewGitHubPullRequests,
        });
      }

      if (onViewGitHubRepository) {
        commands.push({
          id: 'action-view-github-repo',
          label: 'Github: View Repository',
          icon: <SiGithub size={14} />,
          category: 'Actions',
          keywords: ['repo', 'repository', 'github'],
          action: onViewGitHubRepository,
        });
      }

      if (onOpenPROnGitHub || onSwitchToPullRequests) {
        commands.push({
          id: 'action-open-pr-github',
          label: 'Github: View Current Pull Request',
          icon: <GitPullRequest size={14} />,
          category: 'Actions',
          keywords: ['PR', 'pull request', 'Github PR'],
          // Switch to Pull Requests panel (auto-selects current-branch PR)
          action: onSwitchToPullRequests ?? onOpenPROnGitHub!,
        });
      }

      // Git Diff has no global registration here.
      //
      // Per-workspace 'Git: Show Current Changes' commands are contributed by
      // `useWorkspaceCommandItems` (one per workspace). When zero workspaces are
      // registered there's nothing meaningful to diff, so users open the Git
      // Panel via `panel-git` below and pick a workspace from there.

      // ─── Preferences ─────────────────────────────────────────────
      commands.push({
        id: 'action-reset-command-stats',
        label: 'Preferences: Reset Command Stats',
        icon: <Settings size={14} />,
        category: 'Preferences',
        keywords: ['reset', 'clear', 'stats', 'usage', 'frecency'],
        action: () => {
          clearUsage();
          toast.success('Command stats cleared');
        },
      });
    }

    // ─── Panels ──────────────────────────────────────────
    if (onSwitchToSourceControl || onOpenGitPanel) {
      commands.push({
        id: 'panel-git',
        label: 'View: Show Source Control',
        icon: <GitBranch size={14} />,
        category: 'Panels',
        keywords: ['git', 'git panel', 'source control', 'diff', 'history', 'workspace details'],
        action: onSwitchToSourceControl ?? onOpenGitPanel!,
      });
    }

    commands.push(
      {
        id: 'panel-configuration',
        label: 'Preferences: Settings',
        icon: <Settings size={14} />,
        category: 'Preferences',
        keywords: ['settings', 'configuration', 'config', 'preferences'],
        action: () => onOpenSettings('setup'),
      },
      {
        id: 'panel-event-stream',
        label: 'View: Show Event Stream',
        icon: <Activity size={14} />,
        category: 'Panels',
        keywords: ['event', 'events', 'stream', 'activity'],
        action: onOpenEventStream,
      },
      {
        id: 'panel-pending-review',
        label: 'View: Show Pending Review',
        icon: <ClipboardCheck size={14} />,
        category: 'Panels',
        keywords: ['pending', 'review', 'pr review'],
        action: onOpenPendingReview,
      },
      {
        id: 'panel-backlog',
        label: 'View: Show Backlog',
        icon: <ListTodo size={14} />,
        category: 'Panels',
        keywords: ['backlog', 'tasks', 'todo'],
        action: onOpenBacklog,
      }
    );

    if (onCreateBacklogItem) {
      commands.push({
        id: 'action-new-backlog-item',
        label: 'New Backlog Item',
        icon: <Plus size={14} />,
        category: 'Actions',
        keywords: ['create', 'new', 'backlog', 'item', 'task', 'todo', 'add'],
        action: onCreateBacklogItem,
      });
    }

    if (onSwitchToPullRequests || onOpenPRReview) {
      commands.push({
        id: 'panel-pull-requests',
        label: 'View: Show Pull Requests',
        icon: <GitPullRequest size={14} />,
        category: 'Panels',
        keywords: ['PR', 'PRs', 'Review', 'pull requests panel', 'pulls', 'github'],
        action: onSwitchToPullRequests ?? onOpenPRReview!,
      });
    }

    if (onShowExplorer) {
      commands.push({
        id: 'view-explorer',
        label: 'View: Show Explorer',
        icon: <Files size={14} />,
        category: 'Panels',
        keywords: ['files', 'tree', 'explorer', 'workspace'],
        action: onShowExplorer,
      });
    }

    if (onShowMessages) {
      commands.push({
        id: 'view-messages',
        label: 'View: Show Messages',
        icon: <MessagesSquare size={14} />,
        category: 'Panels',
        keywords: ['chat', 'messages', 'feed', 'history'],
        action: onShowMessages,
      });
    }

    if (onToggleChatSplitPanel) {
      commands.push({
        id: 'view-toggle-chat-split-panel',
        label: 'View: Toggle Split Chat',
        icon: <MessageSquare size={14} />,
        category: 'Panels',
        keywords: ['chat', 'split', 'panel', 'messages', 'side', 'toggle'],
        action: onToggleChatSplitPanel,
      });
    }

    // ─── Agents ──────────────────────────────────────────────
    if (onStartAllRemoteAgents) {
      commands.push({
        id: 'agents-start-all-remote',
        label: 'Agents: Start All Remote',
        icon: <Play size={14} />,
        category: 'Agents',
        keywords: ['start', 'remote', 'run', 'launch', 'all'],
        action: onStartAllRemoteAgents,
      });
    }

    if (onStopAllRemoteAgents) {
      commands.push({
        id: 'agents-stop-all-remote',
        label: 'Agents: Stop All Remote',
        icon: <StopCircle size={14} />,
        category: 'Agents',
        keywords: ['stop', 'remote', 'kill', 'terminate', 'all'],
        action: onStopAllRemoteAgents,
      });
    }

    if (onRestartAllRemoteAgents) {
      commands.push({
        id: 'agents-restart-all-remote',
        label: 'Agents: Restart All Remote',
        icon: <RefreshCw size={14} />,
        category: 'Agents',
        keywords: ['restart', 'remote', 'reload', 'refresh', 'all'],
        action: onRestartAllRemoteAgents,
      });
    }

    if (onRestartRemoteAgent && restartableAgentRoles && restartableAgentRoles.length > 0) {
      for (const role of restartableAgentRoles) {
        commands.push({
          id: `agents-restart-${role.toLowerCase()}`,
          label: `Agents: Restart ${toTitleCase(role)}`,
          icon: <RefreshCw size={14} />,
          category: 'Agents',
          keywords: ['restart', 'remote', role, 'reload', 'refresh'],
          action: () => onRestartRemoteAgent(role),
        });
      }
    }

    // ─── Workspace ──────────────────────────────────────────────
    if (onRefreshWorkspaceState) {
      commands.push({
        id: 'action-refresh-workspace-state',
        label: 'Chatroom: Refresh Workspace State',
        icon: <RefreshCw size={14} />,
        category: 'Actions',
        // Omit "pull" / "git pull" — this command re-pushes observed state from the daemon, not VCS pull.
        keywords: [
          'refresh',
          'reload',
          'sync',
          'workspace',
          'state',
          'update',
          'git',
          'observed',
          'daemon',
        ],
        action: onRefreshWorkspaceState,
      });
    }

    // ─── Processes panel ────────────────────────────────
    if (onOpenProcessesPanel) {
      commands.push({
        id: 'panel-processes',
        label: 'View: Show Processes',
        icon: <Terminal size={14} />,
        category: 'Panels',
        keywords: ['processes', 'process manager', 'commands', 'terminal', 'run'],
        action: onOpenProcessesPanel,
      });
    }

    return commands;
  }, [
    onOpenSettings,
    onOpenEventStream,
    onOpenGitPanel,
    onOpenBacklog,
    onOpenPendingReview,
    onCreateBacklogItem,
    onOpenChatroomSwitcher,
    onCreateNewChatroom,
    onOpenFileSelector,
    onOpenInVSCode,
    onOpenInGitHubDesktop,
    onOpenPROnGitHub,
    onOpenPRReview,
    onViewGitHubPullRequests,
    onViewGitHubRepository,
    onOpenWorkspaceDetails,
    runnableCommands,
    onOpenProcessesPanelWithCommand,
    onRunCommand,
    onOpenProcessesPanel,
    onShowExplorer,
    onShowMessages,
    onToggleChatSplitPanel,
    favorites,
    workspaceCommands,
    onStartAllRemoteAgents,
    onStopAllRemoteAgents,
    onRestartAllRemoteAgents,
    restartableAgentRoles,
    onRestartRemoteAgent,
    onCreateCommand,
    savedCommands,
    onExecuteSavedCommand,
    onEditSavedCommand,
    onDeleteSavedCommand,
    confirmingDeleteCommandId,
    onRefreshWorkspaceState,
    onSwitchToSourceControl,
    onSwitchToPullRequests,
    onOpenAgenticSearch,
  ]);
}
